services:
  postgres:
    image: postgres:17
    restart: always
    container_name: mad_maps_db
    environment:
      POSTGRES_DB: mad_maps
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend/mad-maps
    container_name: mad_maps-backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      API_KEY : ${API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_MAPS_API_KEY: ${API_KEY}
    container_name: mad_maps-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local
